### ISSUE TITLE
Css file missing that's why it is messing up

### ISSUE THREAD

**Issue by ishaan019** [DamianArado/test-solutions#1]
Add it

**Comment by DamianArado** [comment]
Buddy, bootstrap file is there! And only that is referenced here in index.html

**Comment by DamianArado** [comment]
You can clone and check as index page is working fine! =)

**Comment by ishaan019** [comment]
Sorry I made a mistake by saying CSS is missing because I don't know the same thing is available in Bootstrap as Alerts.
Thanks for enhancing my knowledge. 🥇 
And I have changed some code in app.js file. Please check it, and I think it will work perfectly.

Thank You 
Ishaan Pasricha
